# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sda_calibration_form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmSDACalibration(object):
    def setupUi(self, frmSDACalibration):
        frmSDACalibration.setObjectName("frmSDACalibration")
        frmSDACalibration.resize(421, 251)
        frmSDACalibration.setMinimumSize(QtCore.QSize(421, 251))
        frmSDACalibration.setMaximumSize(QtCore.QSize(421, 251))
        self.centralwidget = QtWidgets.QWidget(frmSDACalibration)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(-220, -190, 1041, 731))
        self.groupBox_4.setObjectName("groupBox_4")
        self.btnCal_Done = QtWidgets.QPushButton(self.groupBox_4)
        self.btnCal_Done.setGeometry(QtCore.QRect(410, 400, 111, 31))
        self.btnCal_Done.setObjectName("btnCal_Done")
        self.btnCal_ProcessCalibration = QtWidgets.QPushButton(self.groupBox_4)
        self.btnCal_ProcessCalibration.setGeometry(QtCore.QRect(240, 400, 151, 31))
        self.btnCal_ProcessCalibration.setObjectName("btnCal_ProcessCalibration")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 230, 401, 161))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.txtCal_DarkName = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtCal_DarkName.setGeometry(QtCore.QRect(110, 40, 91, 22))
        self.txtCal_DarkName.setObjectName("txtCal_DarkName")
        self.lblCal_RefTemp = QtWidgets.QLabel(self.groupBox_2)
        self.lblCal_RefTemp.setGeometry(QtCore.QRect(-50, 70, 151, 21))
        self.lblCal_RefTemp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCal_RefTemp.setObjectName("lblCal_RefTemp")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(220, 50, 171, 91))
        self.groupBox.setObjectName("groupBox")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(10, 60, 41, 21))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(-10, 30, 61, 21))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.txtCal_MaxCFWL = QtWidgets.QLineEdit(self.groupBox)
        self.txtCal_MaxCFWL.setGeometry(QtCore.QRect(60, 60, 91, 22))
        self.txtCal_MaxCFWL.setObjectName("txtCal_MaxCFWL")
        self.txtCal_MinCFWL = QtWidgets.QLineEdit(self.groupBox)
        self.txtCal_MinCFWL.setGeometry(QtCore.QRect(60, 30, 91, 22))
        self.txtCal_MinCFWL.setObjectName("txtCal_MinCFWL")
        self.txtCal_RefTemp = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtCal_RefTemp.setGeometry(QtCore.QRect(110, 70, 91, 22))
        self.txtCal_RefTemp.setObjectName("txtCal_RefTemp")
        self.lblCal_DarkName = QtWidgets.QLabel(self.groupBox_2)
        self.lblCal_DarkName.setGeometry(QtCore.QRect(-50, 40, 151, 21))
        self.lblCal_DarkName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCal_DarkName.setObjectName("lblCal_DarkName")
        self.txtCal_LampName = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtCal_LampName.setGeometry(QtCore.QRect(110, 10, 91, 22))
        self.txtCal_LampName.setObjectName("txtCal_LampName")
        self.lblCal_SRFName = QtWidgets.QLabel(self.groupBox_2)
        self.lblCal_SRFName.setGeometry(QtCore.QRect(-50, 100, 151, 21))
        self.lblCal_SRFName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCal_SRFName.setObjectName("lblCal_SRFName")
        self.lblCal_LampName = QtWidgets.QLabel(self.groupBox_2)
        self.lblCal_LampName.setGeometry(QtCore.QRect(-50, 10, 151, 21))
        self.lblCal_LampName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCal_LampName.setObjectName("lblCal_LampName")
        self.txtCal_SRFName = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtCal_SRFName.setGeometry(QtCore.QRect(110, 100, 91, 22))
        self.txtCal_SRFName.setObjectName("txtCal_SRFName")
        self.btnCal_LoadFiles = QtWidgets.QPushButton(self.groupBox_2)
        self.btnCal_LoadFiles.setGeometry(QtCore.QRect(220, 10, 131, 31))
        self.btnCal_LoadFiles.setObjectName("btnCal_LoadFiles")
        self.lblCal_CalibrationCheck = QtWidgets.QLabel(self.groupBox_2)
        self.lblCal_CalibrationCheck.setGeometry(QtCore.QRect(-50, 130, 151, 21))
        self.lblCal_CalibrationCheck.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCal_CalibrationCheck.setObjectName("lblCal_CalibrationCheck")
        self.txtCal_CalibrationCheck = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtCal_CalibrationCheck.setGeometry(QtCore.QRect(110, 130, 91, 22))
        self.txtCal_CalibrationCheck.setObjectName("txtCal_CalibrationCheck")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(230, 200, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btnCal_Cancel = QtWidgets.QPushButton(self.groupBox_4)
        self.btnCal_Cancel.setGeometry(QtCore.QRect(540, 400, 81, 31))
        self.btnCal_Cancel.setObjectName("btnCal_Cancel")
        frmSDACalibration.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmSDACalibration)
        QtCore.QMetaObject.connectSlotsByName(frmSDACalibration)
        frmSDACalibration.setTabOrder(self.txtCal_LampName, self.txtCal_DarkName)
        frmSDACalibration.setTabOrder(self.txtCal_DarkName, self.txtCal_RefTemp)
        frmSDACalibration.setTabOrder(self.txtCal_RefTemp, self.txtCal_SRFName)
        frmSDACalibration.setTabOrder(self.txtCal_SRFName, self.txtCal_CalibrationCheck)
        frmSDACalibration.setTabOrder(self.txtCal_CalibrationCheck, self.btnCal_LoadFiles)
        frmSDACalibration.setTabOrder(self.btnCal_LoadFiles, self.txtCal_MinCFWL)
        frmSDACalibration.setTabOrder(self.txtCal_MinCFWL, self.txtCal_MaxCFWL)
        frmSDACalibration.setTabOrder(self.txtCal_MaxCFWL, self.btnCal_ProcessCalibration)
        frmSDACalibration.setTabOrder(self.btnCal_ProcessCalibration, self.btnCal_Done)
        frmSDACalibration.setTabOrder(self.btnCal_Done, self.btnCal_Cancel)

    def retranslateUi(self, frmSDACalibration):
        _translate = QtCore.QCoreApplication.translate
        frmSDACalibration.setWindowTitle(_translate("frmSDACalibration", "Calibrate Spectrometer"))
        self.groupBox_4.setTitle(_translate("frmSDACalibration", "GroupBox"))
        self.btnCal_Done.setText(_translate("frmSDACalibration", "Save and Close"))
        self.btnCal_ProcessCalibration.setText(_translate("frmSDACalibration", "Calibrate Spectrometer"))
        self.txtCal_DarkName.setText(_translate("frmSDACalibration", "D"))
        self.lblCal_RefTemp.setText(_translate("frmSDACalibration", "Reference Temp :"))
        self.groupBox.setTitle(_translate("frmSDACalibration", "Curve Fit Wavelength"))
        self.label_18.setText(_translate("frmSDACalibration", "Max :"))
        self.label_17.setText(_translate("frmSDACalibration", "Min :"))
        self.txtCal_MaxCFWL.setText(_translate("frmSDACalibration", "930"))
        self.txtCal_MinCFWL.setText(_translate("frmSDACalibration", "550"))
        self.lblCal_DarkName.setText(_translate("frmSDACalibration", "Dark Name Prefix :"))
        self.txtCal_LampName.setText(_translate("frmSDACalibration", "L"))
        self.lblCal_SRFName.setText(_translate("frmSDACalibration", "SRF Name :"))
        self.lblCal_LampName.setText(_translate("frmSDACalibration", "Lamp Name Prefix :"))
        self.btnCal_LoadFiles.setText(_translate("frmSDACalibration", "Load Files..."))
        self.lblCal_CalibrationCheck.setText(_translate("frmSDACalibration", "Calibration Check :"))
        self.label_2.setText(_translate("frmSDACalibration", "Calibrate Spectrometer"))
        self.btnCal_Cancel.setText(_translate("frmSDACalibration", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmSDACalibration = QtWidgets.QMainWindow()
    ui = Ui_frmSDACalibration()
    ui.setupUi(frmSDACalibration)
    frmSDACalibration.show()
    sys.exit(app.exec_())

