# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sda_main_form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmSDAMain(object):
    def setupUi(self, frmSDAMain):
        frmSDAMain.setObjectName("frmSDAMain")
        frmSDAMain.resize(400, 320)
        frmSDAMain.setMinimumSize(QtCore.QSize(388, 307))
        frmSDAMain.setMaximumSize(QtCore.QSize(700, 700))
        self.centralwidget = QtWidgets.QWidget(frmSDAMain)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(50, 25, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.btnCalibrateSpectrometerLink = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalibrateSpectrometerLink.setGeometry(QtCore.QRect(100, 290, 191, 31))
        self.btnCalibrateSpectrometerLink.setToolTip("")
        self.btnCalibrateSpectrometerLink.setObjectName("btnCalibrateSpectrometerLink")
        self.lblMinWavelength = QtWidgets.QLabel(self.centralwidget)
        self.lblMinWavelength.setGeometry(QtCore.QRect(-160, 140, 340, 21))
        self.lblMinWavelength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMinWavelength.setObjectName("lblMinWavelength")
        self.lblCalibrationStatus = QtWidgets.QLabel(self.centralwidget)
        self.lblCalibrationStatus.setGeometry(QtCore.QRect(100, 270, 301, 21))
        self.lblCalibrationStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCalibrationStatus.setObjectName("lblCalibrationStatus")
        self.txtAna_MaxADWL = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAna_MaxADWL.setGeometry(QtCore.QRect(190, 170, 101, 22))
        self.txtAna_MaxADWL.setObjectName("txtAna_MaxADWL")
        self.txtAna_MinFraction = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAna_MinFraction.setGeometry(QtCore.QRect(190, 110, 101, 22))
        self.txtAna_MinFraction.setObjectName("txtAna_MinFraction")
        self.txtAna_MinADWL = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAna_MinADWL.setGeometry(QtCore.QRect(190, 140, 101, 22))
        self.txtAna_MinADWL.setObjectName("txtAna_MinADWL")
        self.lblDataFiles = QtWidgets.QLabel(self.centralwidget)
        self.lblDataFiles.setGeometry(QtCore.QRect(-160, 80, 340, 21))
        self.lblDataFiles.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDataFiles.setObjectName("lblDataFiles")
        self.txtAna_PlotWavelength = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAna_PlotWavelength.setGeometry(QtCore.QRect(190, 200, 101, 22))
        self.txtAna_PlotWavelength.setObjectName("txtAna_PlotWavelength")
        self.txtAna_DataFiles = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAna_DataFiles.setEnabled(True)
        self.txtAna_DataFiles.setGeometry(QtCore.QRect(190, 80, 101, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtAna_DataFiles.setPalette(palette)
        self.txtAna_DataFiles.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtAna_DataFiles.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtAna_DataFiles.setFrame(True)
        self.txtAna_DataFiles.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAna_DataFiles.setReadOnly(True)
        self.txtAna_DataFiles.setClearButtonEnabled(False)
        self.txtAna_DataFiles.setObjectName("txtAna_DataFiles")
        self.lblPlotWavelength = QtWidgets.QLabel(self.centralwidget)
        self.lblPlotWavelength.setGeometry(QtCore.QRect(-160, 200, 340, 21))
        self.lblPlotWavelength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPlotWavelength.setObjectName("lblPlotWavelength")
        self.btnAnalyzeData = QtWidgets.QPushButton(self.centralwidget)
        self.btnAnalyzeData.setGeometry(QtCore.QRect(300, 115, 91, 31))
        self.btnAnalyzeData.setObjectName("btnAnalyzeData")
        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setGeometry(QtCore.QRect(300, 185, 91, 31))
        self.btnReset.setObjectName("btnReset")
        self.lblMinFraction = QtWidgets.QLabel(self.centralwidget)
        self.lblMinFraction.setGeometry(QtCore.QRect(-160, 110, 340, 21))
        self.lblMinFraction.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMinFraction.setObjectName("lblMinFraction")
        self.lblMaxWavelength = QtWidgets.QLabel(self.centralwidget)
        self.lblMaxWavelength.setGeometry(QtCore.QRect(-160, 170, 340, 21))
        self.lblMaxWavelength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMaxWavelength.setObjectName("lblMaxWavelength")
        self.btnAna_ViewPlots = QtWidgets.QPushButton(self.centralwidget)
        self.btnAna_ViewPlots.setGeometry(QtCore.QRect(300, 150, 91, 31))
        self.btnAna_ViewPlots.setObjectName("btnAna_ViewPlots")
        self.btnAna_LoadSRF = QtWidgets.QPushButton(self.centralwidget)
        self.btnAna_LoadSRF.setGeometry(QtCore.QRect(290, 290, 112, 31))
        self.btnAna_LoadSRF.setObjectName("btnAna_LoadSRF")
        self.btnAna_LoadData = QtWidgets.QPushButton(self.centralwidget)
        self.btnAna_LoadData.setGeometry(QtCore.QRect(300, 80, 91, 31))
        self.btnAna_LoadData.setObjectName("btnAna_LoadData")
        self.cmbAna_PlotDataFile = QtWidgets.QComboBox(self.centralwidget)
        self.cmbAna_PlotDataFile.setGeometry(QtCore.QRect(190, 230, 101, 25))
        self.cmbAna_PlotDataFile.setObjectName("cmbAna_PlotDataFile")
        self.lblPlotDataFile = QtWidgets.QLabel(self.centralwidget)
        self.lblPlotDataFile.setGeometry(QtCore.QRect(-160, 230, 340, 21))
        self.lblPlotDataFile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPlotDataFile.setObjectName("lblPlotDataFile")
        self.btnAbout = QtWidgets.QPushButton(self.centralwidget)
        self.btnAbout.setGeometry(QtCore.QRect(300, 220, 91, 31))
        self.btnAbout.setObjectName("btnAbout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 51, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/Stratonics logo transparent.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        frmSDAMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmSDAMain)
        QtCore.QMetaObject.connectSlotsByName(frmSDAMain)
        frmSDAMain.setTabOrder(self.txtAna_MinFraction, self.txtAna_MinADWL)
        frmSDAMain.setTabOrder(self.txtAna_MinADWL, self.txtAna_MaxADWL)
        frmSDAMain.setTabOrder(self.txtAna_MaxADWL, self.txtAna_PlotWavelength)
        frmSDAMain.setTabOrder(self.txtAna_PlotWavelength, self.cmbAna_PlotDataFile)
        frmSDAMain.setTabOrder(self.cmbAna_PlotDataFile, self.btnAna_LoadData)
        frmSDAMain.setTabOrder(self.btnAna_LoadData, self.btnAnalyzeData)
        frmSDAMain.setTabOrder(self.btnAnalyzeData, self.btnAna_ViewPlots)
        frmSDAMain.setTabOrder(self.btnAna_ViewPlots, self.btnReset)
        frmSDAMain.setTabOrder(self.btnReset, self.btnAbout)
        frmSDAMain.setTabOrder(self.btnAbout, self.btnCalibrateSpectrometerLink)
        frmSDAMain.setTabOrder(self.btnCalibrateSpectrometerLink, self.btnAna_LoadSRF)
        frmSDAMain.setTabOrder(self.btnAna_LoadSRF, self.txtAna_DataFiles)

    def retranslateUi(self, frmSDAMain):
        _translate = QtCore.QCoreApplication.translate
        frmSDAMain.setWindowTitle(_translate("frmSDAMain", "Stratonics - Spectrometer Data Analysis"))
        self.lblTitle.setText(_translate("frmSDAMain", "Spectrometer Data Analysis"))
        self.btnCalibrateSpectrometerLink.setText(_translate("frmSDAMain", "Calibrate Spectrometer"))
        self.lblMinWavelength.setText(_translate("frmSDAMain", "Minimum Wavelength Range (nm) :"))
        self.lblCalibrationStatus.setText(_translate("frmSDAMain", "Not Calibrated (No SRF Found)"))
        self.txtAna_MaxADWL.setText(_translate("frmSDAMain", "800"))
        self.txtAna_MinFraction.setText(_translate("frmSDAMain", "0.25"))
        self.txtAna_MinADWL.setText(_translate("frmSDAMain", "600"))
        self.lblDataFiles.setText(_translate("frmSDAMain", "Spectrometer Data Files :"))
        self.txtAna_PlotWavelength.setText(_translate("frmSDAMain", "750"))
        self.txtAna_DataFiles.setText(_translate("frmSDAMain", "No files loaded"))
        self.lblPlotWavelength.setText(_translate("frmSDAMain", "Plot Wavelength (nm) :"))
        self.btnAnalyzeData.setText(_translate("frmSDAMain", "Analyze Data"))
        self.btnReset.setText(_translate("frmSDAMain", "Reset"))
        self.lblMinFraction.setText(_translate("frmSDAMain", "Min. Intensity Fraction :"))
        self.lblMaxWavelength.setText(_translate("frmSDAMain", "Maximum Wavelength Range (nm) :"))
        self.btnAna_ViewPlots.setText(_translate("frmSDAMain", "View Plots"))
        self.btnAna_LoadSRF.setText(_translate("frmSDAMain", "Load SRF"))
        self.btnAna_LoadData.setText(_translate("frmSDAMain", "... Load Data"))
        self.lblPlotDataFile.setText(_translate("frmSDAMain", "Plot Z Data File :"))
        self.btnAbout.setText(_translate("frmSDAMain", "About"))

import sda_resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmSDAMain = QtWidgets.QMainWindow()
    ui = Ui_frmSDAMain()
    ui.setupUi(frmSDAMain)
    frmSDAMain.show()
    sys.exit(app.exec_())

